from .curves import get_rank_configs

# Multipliers
VISION_DISTANCE_MULT = 0.9  
VISION_CHECK_TIME_MULT = 1.5 
VISION_LOSE_TIME_MULT = 2 
PLAYER_STEALTH_COMFORT_MULT = 0.8
PLAYER_STEALTH_LOUDNESS_MULT = 0.8
NPC_WEAPON_DISPERSION_MULT = 0.4
NPC_RANGE_MULT = 1.3
COMBAT_DISTANCE_MULT = 1.2
SNIPER_DISPERSION_SCALING = 7.0
PISTOL_DISPERSION_SCALING = 2.5
SMG_DISPERSION_SCALING = 1.9
SNIPER_MAX_DIST_MULT = 0.25
MASTER_SNIPER_MAX_DIST_MULT = 0.35

DEBUG_GUARANTEED_HITS = False

# Rank Configurations (Generated via curves.py)
RANK_CONFIGS = get_rank_configs()

# Bleeding Logic
BLEEDING_BASE_MULT = 0.646
BLEEDING_BASE_ADD = 1.54
BLEEDING_CHANCE_MULT = 0.6
BLEEDING_CHANCE_SUB = 0.01
BLEEDING_CHANCE_MIN_FLOOR = 0.01

# Range Logic
SHOTGUN_MAX_DIST_MULT = 0.75
MIN_DIST_FACTOR = 1.1

# Weapon Defaults & Thresholds
DEFAULT_FSD = 500.0
DEFAULT_MAX_AMMO = 30
MASTER_FSD_THRESHOLD = 160
IGNORE_DISP_LOW_AMMO_THRESHOLD = 4
